apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Fetch Jira Issues and Publish Evidence
# This workflow is designed to fetch Jira issues and publish the evidence
on:
  workflow_dispatch:

jobs:
  fetch-jira-evidence:
    runs-on: ubuntu-latest

    env:
      JIRA_BASE_URL: https://cloudbees.atlassian.net
      JIRA_USER_EMAIL: ${{ secrets.WES_JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.WES_JIRA_API_TOKEN }}
      JQL: 'project = CB-Demo AND summary !~ "Exemption requested by"'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up jq
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq
          version: 1.0

      - name: Verify Jira Connection
        uses: docker://curlimages/curl:latest
        with:
          args: >
            sh -c '
              echo "🔐 Verifying Jira connection...";
              STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" 
                -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" 
                -H "Accept: application/json" 
                "$JIRA_BASE_URL/rest/api/3/myself");
              if [ "$STATUS_CODE" -ne 200 ]; then
                echo "❌ Failed to connect to Jira. Status code: $STATUS_CODE";
                exit 1;
              fi
              echo "✅ Jira connection successful.";
            '

      - name: Query Jira Issues
        uses: docker://curlimages/curl:latest
        with:
          args: >
            sh -c '
              echo "📥 Fetching Jira issues with JQL: $JQL";
              ENCODED_JQL=$(echo "$JQL" | jq -s -R -r @uri);
              RESPONSE=$(curl -s -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" 
                -H "Accept: application/json" 
                "$JIRA_BASE_URL/rest/api/3/search?jql=$ENCODED_JQL");
              echo "$RESPONSE" | jq -r ".issues[] | \"- \(.key): \(.fields.summary)\"" > jira_issues.md;
              echo "📝 Retrieved issues:";
              cat jira_issues.md;
            '

      - name: Publish Jira Query Results to Evidence Tab
        uses: cloudbees-io/attach-evidence@v1
        with:
          name: Jira Issues from CB-Demo
          path: jira_issues.md