apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Synaptics Standard Pipeline
# This is the core Synaptics Pipeline with standard and nested flows
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - Synaptics
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  SynapticsTest1:
    steps:
      - name: Run Jenkins Job
      # This runs the Synaptics Jenkins Pipeline Example
        with:
          url: https://sda.preview.cb-demos.io/bcauthen-demos-mc-1/
          username: ${{ secrets.WES_JENKINS_USERNAME }}
          token: ${{ secrets.WES_JENKINS_TOKEN }}
          job-name: Synaptics_Example
        uses: cloudbees-io/jenkins-run-job@v2
        continue-on-error: true
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Run unit tests
        kind: test
        uses: docker://node:lts
        run: |-
          npm ci
          npm run test:unit
          npx jest --coverage >> $CLOUDBEES_OUTPUTS/CODE_COVERAGE
      - name: Publish test results
        kind: test
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: ${{ cloudbees.workspace }}/junit.xml
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
    outputs:
      CODE_COVERAGE: ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
  NestedPipeline:
    steps:
      - name: Run Nested Jenkins Pipelines
      # This runs the Nested Jenkins Pipelines example
        kind: test
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          url: https://sda.preview.cb-demos.io/bcauthen-demos-mc-1/
          username: ${{ secrets.WES_JENKINS_USERNAME }}
          token: ${{ secrets.WES_JENKINS_TOKEN }}
          job-name: JenkinsPipeline1
    needs: SynapticsTest1
