apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Synaptics Standard Pipeline
# This workflow emulates running the Synaptice Standard Pipeline model
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - Synaptics
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  SynapticsTest1:
    # This is the standard pipeline for Synaptics
    steps:
      - name: Run Jenkins Job
        with:
          url: https://sda.preview.cb-demos.io/bcauthen-demos-mc-1/
          username: ${{ secrets.WES_JENKINS_USERNAME }}
          token: ${{ secrets.WES_JENKINS_TOKEN }}
          job-name: Synaptics_Example
        uses: cloudbees-io/jenkins-run-job@v2
        continue-on-error: true
  NestedPipeline:
    # This is the Nested Jenkins Pipeline for Synaptics
    steps:
      - name: Run Nested Jenkins Pipelines
        kind: test
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          url: https://sda.preview.cb-demos.io/bcauthen-demos-mc-1/
          username: ${{ secrets.WES_JENKINS_USERNAME }}
          token: ${{ secrets.WES_JENKINS_TOKEN }}
          job-name: JenkinsPipeline1
    needs: SynapticsTest1